Moved common backup directory creation logic to backup-rsync.

diff --git a/tools/backup-rsync b/tools/backup-rsync
--- a/tools/backup-rsync
+++ b/tools/backup-rsync
@@ -275,9 +275,12 @@ case ${SSH_ORIGINAL_COMMAND++} in
 	;;
 esac
 
-# Parse server options.
+# Parse options.
+max_dest_opts=20
+unset tag tmp_base
 case ${args}${extra_args} in
-' --server --sender '* )
+' --server --sender '* | \
+' --server --sender'   )
 	case ${backup_prepare} in
 	+ ) "${0%backup*}backup-prepare" || : ;;
 	esac
@@ -285,23 +288,21 @@ case ${args}${extra_args} in
 	do
 		shift
 	done
-	exec "${0%backup*}backup-nice" -- rsync "${@}"
 	;;
-esac
+* )
+	# Parse an internal configuration name option.
+	unset config_name
+	case ${1-} in
+	--backup-config-name=* ) config_name=${1#*=}; shift ;;
+	esac
 
-# Parse an internal configuration name option.
-unset config_name
-case ${1-} in
---backup-config-name=* ) config_name=${1#*=}; shift ;;
-esac
-
-# Construct default option arguments.
-case ${config_name-rsync} in
-create ) filter='dir-merge /.backup-filter' ;;
-*      ) unset filter ;;
-esac
-rsh=${dir}/conf/rsh; [ ! -x "${rsh}" ] && unset rsh
-rsync_path="\
+	# Construct default option arguments.
+	case ${config_name-rsync} in
+	create ) filter='dir-merge /.backup-filter' ;;
+	*      ) unset filter ;;
+	esac
+	rsh=${dir}/conf/rsh; [ ! -x "${rsh}" ] && unset rsh
+	rsync_path="\
 IONICE=\$( command -v -- ionice || : ) && \
 NICE=\$( command -v -- nice || : ) && \
 NOCACHE=\$( command -v -- nocache || : ) && \
@@ -311,35 +312,126 @@ exec \
 \${NOCACHE:+ \"\${NOCACHE}\" -n 2 -- } \
 rsync"
 
-# Extend the options with ones read from configuration files.
-for config_name in ${config_name+ "${config_name}" } rsync
-do
-	[ ! -f "${dir}/conf/${config_name}-config" ] || {
-		for arg
-		do
-			while IFS="${IFS}=" read opt optarg
+	# Extend the options with ones read from configuration files.
+	for config_name in ${config_name+ "${config_name}" } rsync #"
+	do
+		[ ! -f "${dir}/conf/${config_name}-config" ] || {
+			for arg
 			do
-				case ${opt} in
-				'' | '#'*  ) continue ;;
-				filter     ) unset filter ;;
-				rsh        ) unset rsh ;;
-				rsync-path ) unset rsync_path ;;
-				esac
-				set -- "${@}" "--${opt}${optarg:+=${optarg}}"
-			done
-			set -- "${@}" "${arg}"
-			shift
-		done < "${dir}/conf/${config_name}-config"
-	}
-done
+				while IFS="${IFS}=" read opt optarg
+				do
+					case ${opt} in
+					'' | '#'*  ) continue ;;
+					filter     ) unset filter ;;
+					rsh        ) unset rsh ;;
+					rsync-path ) unset rsync_path ;;
+					esac
+					set -- "${@}" "--${opt}${optarg:+=${optarg}}"
+				done
+				set -- "${@}" "${arg}"
+				shift
+			done < "${dir}/conf/${config_name}-config"
+		}
+	done
 
-# Execute.
-exec "${0%backup*}backup-nice" -- rsync \
-	--archive					\
-	${filter+ --filter="${filter}" }		\
-	--fuzzy						\
-	--relative					\
-	${rsh+ --rsh="${rsh}" }				\
-	${rsync_path+ --rsync-path="${rsync_path}" }	\
-	--sparse					\
-	"${@}"
+	# Extend the options with default options.
+	set -- \
+		--archive					\
+		${filter+ --filter="${filter}" }		\
+		--fuzzy						\
+		--relative					\
+		${rsh+ --rsh="${rsh}" }				\
+		${rsync_path+ --rsync-path="${rsync_path}" }	\
+		--sparse					\
+		"${@}"
+
+	# Check if the last operand is <DIR>/tmp/<BASE-PREFIX>-<PID>/<TAG>.
+	eval 'last_arg=${'"${#}"'}'
+	case ${last_arg#"${dir}/tmp/"} in
+	"${last_arg}" | */*[]\(\)\*\/\?\\[]* | */*[![:digit:][:punct:]TW]* ) ;;
+	*-*/[[:digit:]]* )
+		last_arg_dir=${last_arg%/*}
+		tag=${last_arg##*/}
+		tmp_base=${last_arg_dir##*/}
+		;;
+	esac
+	;;
+esac
+
+case ${tmp_base++}${tag++} in
+++ )
+	# Clean up temporary directories.
+	tmp_base_prefix=${tmp_base%-*}
+	"${0%backup*}backup-clean-tmp" -- "${tmp_base_prefix}"
+
+	# Create a protected temporary directory.
+	mkdir -m go= -- "${dir}/tmp/${tmp_base}"
+
+	# Prepare to minimise disk usage and to speed up the transfer.
+	dest_opt=--link-dest
+	fstype=$(
+		exec find "${dir}/." -prune -printf '%F\n' 2> /dev/null
+		) || :
+	if
+		case ${fstype} in
+		btrfs     ) cp_a='cp --archive --reflink=always' ;;
+		fuse.s3ql ) cp_a=s3qlcp ;;
+		*         ) false ;;
+		esac
+	then
+		[ ! -d "${dir}/latest/." ] || {
+			${cp_a} -- \
+				"${dir}/latest/." \
+				"${dir}/tmp/${tmp_base}/${tag}"
+			set -- --delete --delete-delay --delete-excluded "${@}"
+			: > "${dir}/tmp/${tmp_base}/${tag}/.delete-this-file"
+		}
+		dest_opt=--copy-dest
+	fi
+	dest_opts=$(
+		exec ls -t -- "${dir}/" \
+		| exec sed -n \
+			-e '\|[]()*/?\\[]|d' \
+			-e 's|^[[:digit:]][[:digit:][:punct:]TW]*$|'"${dest_opt}"'=../../../&|p' \
+		| exec sed -e '20q'
+		)
+
+	# Run rsync.
+	"${0%backup*}backup-nice" -- rsync ${dest_opts} "${@}" ||
+	case ${?} in
+	24 ) ;; # Partial transfer due to vanished source files
+	*  ) exit 1 ;;
+	esac
+
+	# Release the newly created backup directory.
+	if [ ! -d "${dir}/tmp/${tmp_base}/${tag}" ]
+	then
+		# Dry run.
+		:
+	elif [ -f "${dir}/tmp/${tmp_base}/${tag}/.delete-this-file" ]
+	then
+		# Dry run.
+		case ${fstype} in
+		fuse.s3ql ) s3qlrm -- "${dir}/tmp/${tmp_base}/${tag}" ;;
+		*         ) rm -fr -- "${dir}/tmp/${tmp_base}/${tag}" ;;
+		esac
+	else
+		chmod -- g=u-w,o= "${dir}/tmp/${tmp_base}/${tag}"
+		chgrp -- users    "${dir}/tmp/${tmp_base}/${tag}"
+		case ${fstype} in
+		fuse.s3ql ) s3qllock -- "${dir}/tmp/${tmp_base}/${tag}" ;;
+		esac
+		ln -s -- "${tag}" "${dir}/tmp/${tmp_base}/latest"
+		sync
+		mv -f -- "${dir}/tmp/${tmp_base}"/* "${dir}/"
+		sync
+	fi
+
+	# Remove the protected temporary directory.
+	rmdir -- "${dir}/tmp/${tmp_base}"
+	;;
+* )
+	# Run rsync.
+	exec "${0%backup*}backup-nice" -- rsync "${@}"
+	;;
+esac
