Allowed dry-run.

diff --git a/tools/backup-create b/tools/backup-create
--- a/tools/backup-create
+++ b/tools/backup-create
@@ -1,6 +1,6 @@
 #! /bin/sh -Ceu
 ###########################################################################
-# backup-create 0.0.20211031
+# backup-create 0.0.20211107
 #
 # Copyright (C) 2010-2021 Eero Häkkinen <Eero+rsync-backup@Häkkinen.fi>
 #
@@ -323,15 +323,19 @@ case ${?} in
 24 ) ;; # Partial transfer due to vanished source files
 *  ) exit 1 ;;
 esac
-chmod -- g=u-w,o= "${dir}/tmp/create-${tmp_tag}-${$}/${tag}"
-chgrp -- users    "${dir}/tmp/create-${tmp_tag}-${$}/${tag}"
-case ${fstype} in
-fuse.s3ql ) s3qllock -- "${dir}/tmp/create-${tmp_tag}-${$}/${tag}" ;;
-esac
+[ ! -d "${dir}/tmp/create-${tmp_tag}-${$}/${tag}" ] || {
+	chmod -- g=u-w,o= "${dir}/tmp/create-${tmp_tag}-${$}/${tag}"
+	chgrp -- users    "${dir}/tmp/create-${tmp_tag}-${$}/${tag}"
+	case ${fstype} in
+	fuse.s3ql ) s3qllock -- "${dir}/tmp/create-${tmp_tag}-${$}/${tag}" ;;
+	esac
 
-# Release the newly created backup directory.
-ln    -s -- "${tag}" "${dir}/tmp/create-${tmp_tag}-${$}/latest"
-sync
-mv    -f -- "${dir}/tmp/create-${tmp_tag}-${$}"/* "${dir}/"
-rmdir    -- "${dir}/tmp/create-${tmp_tag}-${$}"
-sync
+	# Release the newly created backup directory.
+	ln -s -- "${tag}" "${dir}/tmp/create-${tmp_tag}-${$}/latest"
+	sync
+	mv -f -- "${dir}/tmp/create-${tmp_tag}-${$}"/* "${dir}/"
+	sync
+}
+
+# Clean up.
+rmdir -- "${dir}/tmp/create-${tmp_tag}-${$}"
